### ISSUE TITLE
Gender fluidity

### ISSUE THREAD

**Issue by roymckenzie** [MarkDunne/33-questions#10]
As it is becomes more socially acceptable to identify in a [gender fluid](http://en.wikipedia.org/wiki/Genderqueer) fashion, having gender/sex as a question may not be ideal as it is not universally considered binary. Just a thought!

**Comment by tklovett** [comment]
Perhaps rephrasing it to "Do you identify as male?" would address that concern while still dividing the population roughly in half.

**Comment by roymckenzie** [comment]
@tklovett :+1:
