### ISSUE TITLE
Questions should be temporally stable

### ISSUE THREAD

**Issue by jcdickinson** [MarkDunne/33-questions#57]
The second question is an example of this.

> Do you currently live in one of the following countries: China, India, The United States, Indonesia, Brazil or Pakistan?

If a person were to move they would stand the chance of having the same identity as someone else. The correct question would be:

> Were you born in one of the following countries: China, India, The United States, Indonesia, Brazil or Pakistan?

**Comment by thibaultcha** [comment]
Duplicate #33
